export type ApiPriority = "P0" | "P1" | "조건부";
export type SessionUse = "제작" | "탐구" | "공통";
export type StoragePolicy = "DB화" | "캐시" | "실시간" | "선택";
export type AuthType = "없음" | "API 키" | "키 쌍" | "모듈별 키";
export type KeyVisibility = "없음" | "브라우저 도메인" | "서버 전용";

export interface ApiDefinition {
  id: string;
  provider: string;
  name: string;
  priority: ApiPriority;
  sessionUse: SessionUse[];
  auth: AuthType;
  keyEnv: string[];
  keyVisibility: KeyVisibility;
  limit: string;
  terms: string;
  storage: StoragePolicy;
  role: string;
  officialUrl: string;
  implementationNote: string;
}

export const apiRegistry: ApiDefinition[] = [
  {
    id: "kosis",
    provider: "KOSIS",
    name: "국가통계포털 공유서비스",
    priority: "P0",
    sessionUse: ["제작", "탐구"],
    auth: "API 키",
    keyEnv: ["KOSIS_API_KEY"],
    keyVisibility: "서버 전용",
    limit: "공식 공개값: 200회/분, 40,000셀/요청(XLS는 200,000셀)",
    terms: "출처·저작권 표시, 키 보호, 원자료 유료 재배포 금지",
    storage: "DB화",
    role: "인구·산업·지역 격차의 시계열·횡단면 통계",
    officialUrl: "https://kosis.kr/openapi/introduce/introduce_01List.do",
    implementationNote: "선정한 통계표의 메타데이터와 관측값을 Supabase 스냅샷으로 적재",
  },
  {
    id: "sgis-data",
    provider: "SGIS",
    name: "통계지리정보서비스 데이터 API",
    priority: "P0",
    sessionUse: ["제작", "탐구"],
    auth: "키 쌍",
    keyEnv: ["SGIS_CONSUMER_KEY", "SGIS_CONSUMER_SECRET"],
    keyVisibility: "서버 전용",
    limit: "테스트 키 즉시 사용, 상업 키는 승인 필요; 세부 엔드포인트별 제한 재검증",
    terms: "개발자 이용약관·상업 이용 조건 및 원출처 표시 확인",
    storage: "DB화",
    role: "행정구역 통계·경계·공간분석용 기초자료",
    officialUrl: "https://sgis.mods.go.kr/developer/html/home.html",
    implementationNote: "지도 타일 렌더링보다 통계·경계 원자료 수집 어댑터를 우선",
  },
  {
    id: "vworld-2d",
    provider: "VWorld",
    name: "2D 지도·공간검색",
    priority: "P0",
    sessionUse: ["제작", "탐구"],
    auth: "API 키",
    keyEnv: ["VITE_VWORLD_API_KEY", "VITE_VWORLD_DOMAIN"],
    keyVisibility: "브라우저 도메인",
    limit: "지오코더 공식 제한: 40,000건/일; 기타 API는 과다 호출 시 차단 가능",
    terms: "개발키는 연구·개인 개발, 운영 서비스는 운영키·등록 도메인 확인",
    storage: "실시간",
    role: "2D 단계구분도·점·선·면·주소 검색·레이어 비교",
    officialUrl: "https://www.vworld.kr/dev/v4dv_opn2dmap2guide_s001.do",
    implementationNote: "OpenLayers 기반 2D 작업공간을 /create/2d와 /inquiry/2d로 독립",
  },
  {
    id: "vworld-3d",
    provider: "VWorld",
    name: "WebGL 3D 지도",
    priority: "P0",
    sessionUse: ["제작", "탐구"],
    auth: "API 키",
    keyEnv: ["VITE_VWORLD_API_KEY", "VITE_VWORLD_DOMAIN"],
    keyVisibility: "브라우저 도메인",
    limit: "지오코더 공식 제한: 40,000건/일; 기타 API는 과다 호출 시 차단 가능",
    terms: "WebGL 3D 가이드·등록 도메인·운영키 조건을 실제 초기화 전에 재확인",
    storage: "실시간",
    role: "지형·고도·입체 도시·경관·재해 취약성 탐구",
    officialUrl: "https://www.vworld.kr/dev/v4dv_opnws3dmap3guide_s001.do",
    implementationNote: "Cesium/WebGL 의존성을 2D 번들에서 분리하고 성능 예산을 별도 관리",
  },
  {
    id: "juso",
    provider: "도로명주소",
    name: "주소 검색·좌표·상세·지도 모듈",
    priority: "P0",
    sessionUse: ["제작", "탐구"],
    auth: "모듈별 키",
    keyEnv: [
      "JUSO_CONFIRM_KEY",
      "JUSO_COORDINATE_KEY",
      "JUSO_DETAIL_KEY",
      "JUSO_MAP_KEY",
    ],
    keyVisibility: "서버 전용",
    limit: "좌표 API 10회/5초; 주소 검색은 고정값 없이 과다·공격성 호출 시 차단 가능",
    terms: "신청한 모듈의 이용조건과 호출 목적을 일치시키고 좌표계 변환 기록",
    storage: "캐시",
    role: "주소 입력을 학습지점·현장조사 위치·지오코딩 결과로 변환",
    officialUrl: "https://business.juso.go.kr/",
    implementationNote: "현재 키는 비워두고, 기능 요구가 확정된 모듈만 추가 신청",
  },
  {
    id: "kma-hub",
    provider: "기상청 API 허브",
    name: "ASOS 관측·기후 통계",
    priority: "P0",
    sessionUse: ["제작", "탐구"],
    auth: "API 키",
    keyEnv: ["KMA_AUTH_KEY"],
    keyVisibility: "서버 전용",
    limit: "일반 20,000회/일·5GB, 기관 30,000회/일·50GB; 기간 조회 최대 31일",
    terms: "키 양도 금지, 공공누리 및 API 허브 이용조건 확인; 제한은 변경될 수 있음",
    storage: "DB화",
    role: "최근 10년 도시 기후·극한기후·계절성·기후지역 비교",
    officialUrl: "https://apihub.kma.go.kr/apiInfo.do",
    implementationNote: "관측소·기간·변수 조합을 사전 정의하고 배치 적재 후 교육용 파생지표 생성",
  },
  {
    id: "kma-short",
    provider: "공공데이터포털·기상청",
    name: "단기예보",
    priority: "P0",
    sessionUse: ["탐구"],
    auth: "API 키",
    keyEnv: ["DATA_GO_KR_SERVICE_KEY"],
    keyVisibility: "서버 전용",
    limit: "개발계정 10,000회/일, 초당 제한 오류 가능; 운영 증량은 활용신청",
    terms: "공공누리 유형 1, 무료 이용·출처 표시",
    storage: "캐시",
    role: "현재 날씨·예보 판단·기상 의사결정 시뮬레이션",
    officialUrl: "https://www.data.go.kr/data/15084084/openapi.do",
    implementationNote: "URL 인코딩된 서비스키를 한 번만 정규화하고 예보 응답은 짧은 TTL 캐시",
  },
  {
    id: "airkorea",
    provider: "에어코리아",
    name: "대기질·미세먼지",
    priority: "P0",
    sessionUse: ["탐구"],
    auth: "API 키",
    keyEnv: ["DATA_GO_KR_SERVICE_KEY"],
    keyVisibility: "서버 전용",
    limit: "개발계정 500회/일; 운영 증량은 활용신청",
    terms: "공공누리 유형 3: 출처 표시·변경 금지 조건 확인",
    storage: "캐시",
    role: "도시환경·건강·산업·기상 조건을 연결한 공간 탐구",
    officialUrl: "https://www.data.go.kr/data/15073861/openapi.do",
    implementationNote: "키 추가 전에는 fixture로 탐구 UI를 개발하고, 이후 관측소·권역 캐시를 연결",
  },
  {
    id: "tourapi",
    provider: "한국관광공사",
    name: "TourAPI 관광·이미지 자료",
    priority: "P0",
    sessionUse: ["제작", "탐구"],
    auth: "API 키",
    keyEnv: ["DATA_GO_KR_SERVICE_KEY"],
    keyVisibility: "서버 전용",
    limit: "페이지상 API 이용 제한 없음, 개발계정 1,000회; 운영 증량은 활용신청",
    terms: "텍스트·이미지별 공공누리 유형과 이미지 재이용 조건을 레코드별 보존",
    storage: "캐시",
    role: "지역 자원 카드·현장조사 자료·관광지 분포 탐구",
    officialUrl: "https://www.data.go.kr/data/15101578/openapi.do",
    implementationNote: "이미지 URL과 라이선스 메타데이터를 함께 저장하고 무단 재배포하지 않음",
  },
  {
    id: "open-meteo",
    provider: "Open-Meteo",
    name: "글로벌 기상·기후 보완자료",
    priority: "P0",
    sessionUse: ["제작", "탐구"],
    auth: "없음",
    keyEnv: [],
    keyVisibility: "없음",
    limit: "무료 비상업: 600회/분·5,000회/시·10,000회/일·300,000회/월",
    terms: "비상업·교육/공공연구 조건, CC BY 4.0 출처 표시; Historical/Climate은 요금제 확인",
    storage: "DB화",
    role: "국가·도시 간 기후 비교와 세계지리 확장",
    officialUrl: "https://open-meteo.com/en/pricing",
    implementationNote: "반복 조회하지 않고 도시·기간별 사전 수집하여 교육용 스냅샷으로 제공",
  },
  {
    id: "world-bank",
    provider: "World Bank",
    name: "세계개발지표",
    priority: "P0",
    sessionUse: ["제작", "탐구"],
    auth: "없음",
    keyEnv: [],
    keyVisibility: "없음",
    limit: "키 불필요, 호출당 지표 최대 60개; SDMX 호출 최대 15,000 datapoints",
    terms: "기본 CC BY 4.0, 제3자 자료 예외와 출처·지표 메타데이터 보존",
    storage: "DB화",
    role: "인구·도시화·경제·환경 지표의 국가 비교",
    officialUrl: "https://datahelpdesk.worldbank.org/knowledgebase/articles/898581",
    implementationNote: "지표 코드·단위·연도·결측 처리 규칙을 함께 저장하고 차트 제작에 재사용",
  },
  {
    id: "usgs",
    provider: "USGS",
    name: "지진·재해 피드",
    priority: "P0",
    sessionUse: ["탐구"],
    auth: "없음",
    keyEnv: [],
    keyVisibility: "없음",
    limit: "고정 수치 미공개; 429 rate limit 가능, 피드·응답은 60초 캐시",
    terms: "공식 피드 이용, 자동화 요청량 절제, 출처와 시각 보존",
    storage: "캐시",
    role: "판 구조·위험·재난 대응 의사결정",
    officialUrl: "https://earthquake.usgs.gov/fdsnws/event/1/",
    implementationNote: "학습 세션 시작 시점 스냅샷을 사용해 활동 중 데이터가 바뀌는 문제를 통제",
  },
  {
    id: "opentopodata",
    provider: "OpenTopoData",
    name: "고도 조회",
    priority: "P0",
    sessionUse: ["제작"],
    auth: "없음",
    keyEnv: [],
    keyVisibility: "없음",
    limit: "100개 위치/요청, 1회/초, 1,000회/일",
    terms: "서비스별 데이터셋 출처와 API 조건 표시",
    storage: "캐시",
    role: "고도 프로파일·지형 단면·3D 지도 설명자료",
    officialUrl: "https://www.opentopodata.org/api/",
    implementationNote: "점 단위 호출을 묶음 요청으로 만들고 제작 결과에는 고도 출처를 첨부",
  },
  {
    id: "gbif",
    provider: "GBIF",
    name: "생물다양성 분포",
    priority: "P1",
    sessionUse: ["탐구"],
    auth: "없음",
    keyEnv: [],
    keyVisibility: "없음",
    limit: "검색 페이지 최대 300, hard limit 100,000; 부하에 따른 429, 다운로드는 인증 필요",
    terms: "레코드별 라이선스·publisher identifier·DOI 보존",
    storage: "DB화",
    role: "생태·환경·보전지역 공간 탐구",
    officialUrl: "https://techdocs.gbif.org/en/openapi/",
    implementationNote: "P1 확장 기능으로 두고 국가·분류군·시기 필터가 확정된 뒤 수집",
  },
  {
    id: "nominatim",
    provider: "OpenStreetMap Nominatim",
    name: "보조 지오코더",
    priority: "P1",
    sessionUse: ["제작", "탐구"],
    auth: "없음",
    keyEnv: [],
    keyVisibility: "없음",
    limit: "1회/초, 유효 User-Agent/Referer 필수; autocomplete·대량·체계적 요청 금지",
    terms: "OSM attribution·ODbL 및 공용 서버 정책 준수",
    storage: "캐시",
    role: "해외 주소 보조 검색·좌표 확인",
    officialUrl: "https://operations.osmfoundation.org/policies/nominatim/",
    implementationNote: "한국 주소는 도로명주소/VWorld를 우선하고 해외 소량 보조 검색에만 사용",
  },
  {
    id: "ev",
    provider: "공공데이터포털·환경부",
    name: "전기차 충전소 현황",
    priority: "P1",
    sessionUse: ["탐구"],
    auth: "API 키",
    keyEnv: ["DATA_GO_KR_SERVICE_KEY"],
    keyVisibility: "서버 전용",
    limit: "개발계정 1,000회; 운영 증량은 활용신청",
    terms: "공공누리 유형 1, 출처 표시",
    storage: "캐시",
    role: "에너지 전환·접근성·생활권 분석",
    officialUrl: "https://www.data.go.kr/data/15076352/openapi.do",
    implementationNote: "충전소 위치와 상태를 분리하고 수업용 시점 스냅샷으로 고정",
  },
  {
    id: "sgis-map-legacy",
    provider: "SGIS",
    name: "SGIS 지도 API/모바일 SDK",
    priority: "조건부",
    sessionUse: ["제작", "탐구"],
    auth: "API 키",
    keyEnv: ["SGIS_CONSUMER_KEY", "SGIS_CONSUMER_SECRET"],
    keyVisibility: "브라우저 도메인",
    limit: "공식 안내에 2025-12-31 서비스 종료 예정 문구가 있어 현재 사용 가능 여부 재확인",
    terms: "종료·대체 API 여부를 확인하기 전 핵심 경로에 의존하지 않음",
    storage: "선택",
    role: "SGIS 전용 지도 기능이 살아 있을 때만 실험적으로 사용",
    officialUrl: "https://sgis.mods.go.kr/developer/html/newOpenApi/api/mapApi/ready.html",
    implementationNote: "지도 렌더링은 VWorld 2D/3D를 기본값으로 유지",
  },
];

export const priorityLabels: Record<ApiPriority, string> = {
  P0: "MVP 핵심",
  P1: "확장",
  조건부: "재검증 후",
};

export const getApiDefinition = (id: string): ApiDefinition | undefined => {
  return apiRegistry.find((api) => api.id === id);
};
